-- Rename Prisma-managed identifiers to plural snake_case without rebuilding or copying data.
-- Constraint and index renames keep the mapped Prisma schema aligned with PostgreSQL metadata.

ALTER TABLE "User" RENAME TO "users";
ALTER TABLE "Workspace" RENAME TO "workspaces";
ALTER TABLE "Session" RENAME TO "sessions";
ALTER TABLE "Vendor" RENAME TO "vendors";
ALTER TABLE "VendorFollow" RENAME TO "vendor_follows";
ALTER TABLE "SavedListing" RENAME TO "saved_listings";
ALTER TABLE "SavedSearch" RENAME TO "saved_searches";
ALTER TABLE "DiscoveryPreference" RENAME TO "discovery_preferences";
ALTER TABLE "Listing" RENAME TO "listings";
ALTER TABLE "ListingVariant" RENAME TO "listing_variants";
ALTER TABLE "ListingRevision" RENAME TO "listing_revisions";
ALTER TABLE "MediaAsset" RENAME TO "media_assets";
ALTER TABLE "CatalogImportJob" RENAME TO "catalog_import_jobs";
ALTER TABLE "CatalogImportRow" RENAME TO "catalog_import_rows";
ALTER TABLE "SearchDocument" RENAME TO "search_documents";
ALTER TABLE "Location" RENAME TO "locations";
ALTER TABLE "VendorMembership" RENAME TO "vendor_memberships";
ALTER TABLE "Staff" RENAME TO "staff_members";
ALTER TABLE "IdempotencyRecord" RENAME TO "idempotency_records";
ALTER TABLE "OutboxEvent" RENAME TO "outbox_events";
ALTER TABLE "ProviderInboxEvent" RENAME TO "provider_inbox_events";
ALTER TABLE "DemoWorkspace" RENAME TO "demo_workspaces";
ALTER TABLE "DemoPersona" RENAME TO "demo_personas";
ALTER TABLE "AuditLog" RENAME TO "audit_logs";
ALTER TABLE "OutboxReceipt" RENAME TO "outbox_receipts";
ALTER TABLE "users" RENAME COLUMN "adultVerificationState" TO "adult_verification_state";
ALTER TABLE "users" RENAME COLUMN "verifiedAt" TO "verified_at";
ALTER TABLE "users" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "workspaces" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "sessions" RENAME COLUMN "userId" TO "user_id";
ALTER TABLE "sessions" RENAME COLUMN "demoPersonaId" TO "demo_persona_id";
ALTER TABLE "sessions" RENAME COLUMN "workspaceId" TO "workspace_id";
ALTER TABLE "sessions" RENAME COLUMN "expiresAt" TO "expires_at";
ALTER TABLE "sessions" RENAME COLUMN "revokedAt" TO "revoked_at";
ALTER TABLE "sessions" RENAME COLUMN "mfaVerifiedAt" TO "mfa_verified_at";
ALTER TABLE "sessions" RENAME COLUMN "recentAuthAt" TO "recent_auth_at";
ALTER TABLE "sessions" RENAME COLUMN "activeVendorId" TO "active_vendor_id";
ALTER TABLE "sessions" RENAME COLUMN "activeRole" TO "active_role";
ALTER TABLE "sessions" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "vendors" RENAME COLUMN "workspaceId" TO "workspace_id";
ALTER TABLE "vendors" RENAME COLUMN "publicSlug" TO "public_slug";
ALTER TABLE "vendors" RENAME COLUMN "publishedAt" TO "published_at";
ALTER TABLE "vendors" RENAME COLUMN "applicationState" TO "application_state";
ALTER TABLE "vendors" RENAME COLUMN "applicationReviewedAt" TO "application_reviewed_at";
ALTER TABLE "vendors" RENAME COLUMN "displayName" TO "display_name";
ALTER TABLE "vendors" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "vendor_follows" RENAME COLUMN "userId" TO "user_id";
ALTER TABLE "vendor_follows" RENAME COLUMN "vendorId" TO "vendor_id";
ALTER TABLE "vendor_follows" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "saved_listings" RENAME COLUMN "userId" TO "user_id";
ALTER TABLE "saved_listings" RENAME COLUMN "listingId" TO "listing_id";
ALTER TABLE "saved_listings" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "saved_searches" RENAME COLUMN "userId" TO "user_id";
ALTER TABLE "saved_searches" RENAME COLUMN "workspaceId" TO "workspace_id";
ALTER TABLE "saved_searches" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "discovery_preferences" RENAME COLUMN "userId" TO "user_id";
ALTER TABLE "discovery_preferences" RENAME COLUMN "workspaceId" TO "workspace_id";
ALTER TABLE "discovery_preferences" RENAME COLUMN "personalizationOptIn" TO "personalization_opt_in";
ALTER TABLE "discovery_preferences" RENAME COLUMN "updatedAt" TO "updated_at";
ALTER TABLE "listings" RENAME COLUMN "vendorId" TO "vendor_id";
ALTER TABLE "listings" RENAME COLUMN "priceCents" TO "price_cents";
ALTER TABLE "listings" RENAME COLUMN "durationMinutes" TO "duration_minutes";
ALTER TABLE "listings" RENAME COLUMN "publishedAt" TO "published_at";
ALTER TABLE "listings" RENAME COLUMN "unpublishedAt" TO "unpublished_at";
ALTER TABLE "listings" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "listings" RENAME COLUMN "updatedAt" TO "updated_at";
ALTER TABLE "listing_variants" RENAME COLUMN "listingId" TO "listing_id";
ALTER TABLE "listing_variants" RENAME COLUMN "priceCents" TO "price_cents";
ALTER TABLE "listing_variants" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "listing_revisions" RENAME COLUMN "listingId" TO "listing_id";
ALTER TABLE "listing_revisions" RENAME COLUMN "reviewedBy" TO "reviewed_by";
ALTER TABLE "listing_revisions" RENAME COLUMN "reviewNote" TO "review_note";
ALTER TABLE "listing_revisions" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "media_assets" RENAME COLUMN "listingId" TO "listing_id";
ALTER TABLE "media_assets" RENAME COLUMN "captionText" TO "caption_text";
ALTER TABLE "media_assets" RENAME COLUMN "noSpeechDeclared" TO "no_speech_declared";
ALTER TABLE "media_assets" RENAME COLUMN "quarantineReason" TO "quarantine_reason";
ALTER TABLE "media_assets" RENAME COLUMN "processedAt" TO "processed_at";
ALTER TABLE "media_assets" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "catalog_import_jobs" RENAME COLUMN "vendorId" TO "vendor_id";
ALTER TABLE "catalog_import_jobs" RENAME COLUMN "templateVersion" TO "template_version";
ALTER TABLE "catalog_import_jobs" RENAME COLUMN "sourceHash" TO "source_hash";
ALTER TABLE "catalog_import_jobs" RENAME COLUMN "rowCount" TO "row_count";
ALTER TABLE "catalog_import_jobs" RENAME COLUMN "validRowCount" TO "valid_row_count";
ALTER TABLE "catalog_import_jobs" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "catalog_import_jobs" RENAME COLUMN "committedAt" TO "committed_at";
ALTER TABLE "catalog_import_rows" RENAME COLUMN "importJobId" TO "import_job_id";
ALTER TABLE "catalog_import_rows" RENAME COLUMN "rowNumber" TO "row_number";
ALTER TABLE "catalog_import_rows" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "search_documents" RENAME COLUMN "listingId" TO "listing_id";
ALTER TABLE "search_documents" RENAME COLUMN "projectedAt" TO "projected_at";
ALTER TABLE "locations" RENAME COLUMN "vendorId" TO "vendor_id";
ALTER TABLE "vendor_memberships" RENAME COLUMN "userId" TO "user_id";
ALTER TABLE "vendor_memberships" RENAME COLUMN "vendorId" TO "vendor_id";
ALTER TABLE "vendor_memberships" RENAME COLUMN "staffId" TO "staff_id";
ALTER TABLE "vendor_memberships" RENAME COLUMN "locationIds" TO "location_ids";
ALTER TABLE "vendor_memberships" RENAME COLUMN "revokedAt" TO "revoked_at";
ALTER TABLE "staff_members" RENAME COLUMN "vendorId" TO "vendor_id";
ALTER TABLE "staff_members" RENAME COLUMN "userId" TO "user_id";
ALTER TABLE "staff_members" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "idempotency_records" RENAME COLUMN "scopeHash" TO "scope_hash";
ALTER TABLE "idempotency_records" RENAME COLUMN "workspaceId" TO "workspace_id";
ALTER TABLE "idempotency_records" RENAME COLUMN "requestHash" TO "request_hash";
ALTER TABLE "idempotency_records" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "idempotency_records" RENAME COLUMN "expiresAt" TO "expires_at";
ALTER TABLE "outbox_events" RENAME COLUMN "eventId" TO "event_id";
ALTER TABLE "outbox_events" RENAME COLUMN "workspaceId" TO "workspace_id";
ALTER TABLE "outbox_events" RENAME COLUMN "claimedBy" TO "claimed_by";
ALTER TABLE "outbox_events" RENAME COLUMN "claimedAt" TO "claimed_at";
ALTER TABLE "outbox_events" RENAME COLUMN "claimToken" TO "claim_token";
ALTER TABLE "outbox_events" RENAME COLUMN "availableAt" TO "available_at";
ALTER TABLE "outbox_events" RENAME COLUMN "occurredAt" TO "occurred_at";
ALTER TABLE "outbox_events" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "provider_inbox_events" RENAME COLUMN "workspaceId" TO "workspace_id";
ALTER TABLE "provider_inbox_events" RENAME COLUMN "providerEventId" TO "provider_event_id";
ALTER TABLE "provider_inbox_events" RENAME COLUMN "providerReference" TO "provider_reference";
ALTER TABLE "provider_inbox_events" RENAME COLUMN "payloadHash" TO "payload_hash";
ALTER TABLE "provider_inbox_events" RENAME COLUMN "reconciliationState" TO "reconciliation_state";
ALTER TABLE "provider_inbox_events" RENAME COLUMN "reconciledAt" TO "reconciled_at";
ALTER TABLE "provider_inbox_events" RENAME COLUMN "receivedAt" TO "received_at";
ALTER TABLE "provider_inbox_events" RENAME COLUMN "processedAt" TO "processed_at";
ALTER TABLE "demo_workspaces" RENAME COLUMN "workspaceId" TO "workspace_id";
ALTER TABLE "demo_workspaces" RENAME COLUMN "providerEventsUsed" TO "provider_events_used";
ALTER TABLE "demo_workspaces" RENAME COLUMN "providerEventsLimit" TO "provider_events_limit";
ALTER TABLE "demo_workspaces" RENAME COLUMN "expiresAt" TO "expires_at";
ALTER TABLE "demo_workspaces" RENAME COLUMN "purgedAt" TO "purged_at";
ALTER TABLE "demo_workspaces" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "demo_personas" RENAME COLUMN "workspaceId" TO "workspace_id";
ALTER TABLE "demo_personas" RENAME COLUMN "vendorId" TO "vendor_id";
ALTER TABLE "demo_personas" RENAME COLUMN "locationIds" TO "location_ids";
ALTER TABLE "demo_personas" RENAME COLUMN "commandEventsUsed" TO "command_events_used";
ALTER TABLE "demo_personas" RENAME COLUMN "commandEventsLimit" TO "command_events_limit";
ALTER TABLE "demo_personas" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "audit_logs" RENAME COLUMN "workspaceId" TO "workspace_id";
ALTER TABLE "audit_logs" RENAME COLUMN "actorId" TO "actor_id";
ALTER TABLE "audit_logs" RENAME COLUMN "correlationId" TO "correlation_id";
ALTER TABLE "audit_logs" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "outbox_receipts" RENAME COLUMN "eventId" TO "event_id";
ALTER TABLE "outbox_receipts" RENAME COLUMN "workspaceId" TO "workspace_id";
ALTER TABLE "outbox_receipts" RENAME COLUMN "processedAt" TO "processed_at";

ALTER TABLE "users" RENAME CONSTRAINT "User_pkey" TO "users_pkey";
ALTER TABLE "users" RENAME CONSTRAINT "User_email_key" TO "users_email_key";
ALTER TABLE "workspaces" RENAME CONSTRAINT "Workspace_pkey" TO "workspaces_pkey";
ALTER TABLE "sessions" RENAME CONSTRAINT "Session_pkey" TO "sessions_pkey";
ALTER TABLE "sessions" RENAME CONSTRAINT "Session_userId_fkey" TO "sessions_user_id_fkey";
ALTER TABLE "sessions" RENAME CONSTRAINT "Session_demoPersonaId_fkey" TO "sessions_demo_persona_id_fkey";
ALTER TABLE "sessions" RENAME CONSTRAINT "Session_workspaceId_fkey" TO "sessions_workspace_id_fkey";
ALTER TABLE "sessions" RENAME CONSTRAINT "Session_activeVendorId_fkey" TO "sessions_active_vendor_id_fkey";
ALTER TABLE "vendors" RENAME CONSTRAINT "Vendor_pkey" TO "vendors_pkey";
ALTER TABLE "vendors" RENAME CONSTRAINT "Vendor_publicSlug_key" TO "vendors_public_slug_key";
ALTER TABLE "vendors" RENAME CONSTRAINT "Vendor_workspaceId_fkey" TO "vendors_workspace_id_fkey";
ALTER TABLE "vendor_follows" RENAME CONSTRAINT "VendorFollow_pkey" TO "vendor_follows_pkey";
ALTER TABLE "vendor_follows" RENAME CONSTRAINT "VendorFollow_userId_fkey" TO "vendor_follows_user_id_fkey";
ALTER TABLE "vendor_follows" RENAME CONSTRAINT "VendorFollow_vendorId_fkey" TO "vendor_follows_vendor_id_fkey";
ALTER TABLE "saved_listings" RENAME CONSTRAINT "SavedListing_pkey" TO "saved_listings_pkey";
ALTER TABLE "saved_listings" RENAME CONSTRAINT "SavedListing_userId_fkey" TO "saved_listings_user_id_fkey";
ALTER TABLE "saved_listings" RENAME CONSTRAINT "SavedListing_listingId_fkey" TO "saved_listings_listing_id_fkey";
ALTER TABLE "saved_searches" RENAME CONSTRAINT "SavedSearch_pkey" TO "saved_searches_pkey";
ALTER TABLE "saved_searches" RENAME CONSTRAINT "SavedSearch_userId_fkey" TO "saved_searches_user_id_fkey";
ALTER TABLE "discovery_preferences" RENAME CONSTRAINT "DiscoveryPreference_pkey" TO "discovery_preferences_pkey";
ALTER TABLE "discovery_preferences" RENAME CONSTRAINT "DiscoveryPreference_userId_fkey" TO "discovery_preferences_user_id_fkey";
ALTER TABLE "listings" RENAME CONSTRAINT "Listing_pkey" TO "listings_pkey";
ALTER TABLE "listings" RENAME CONSTRAINT "Listing_vendorId_fkey" TO "listings_vendor_id_fkey";
ALTER TABLE "listing_variants" RENAME CONSTRAINT "ListingVariant_pkey" TO "listing_variants_pkey";
ALTER TABLE "listing_variants" RENAME CONSTRAINT "ListingVariant_listingId_fkey" TO "listing_variants_listing_id_fkey";
ALTER TABLE "listing_variants" RENAME CONSTRAINT "ListingVariant_listingId_sku_key" TO "listing_variants_listing_id_sku_key";
ALTER TABLE "listing_revisions" RENAME CONSTRAINT "ListingRevision_pkey" TO "listing_revisions_pkey";
ALTER TABLE "listing_revisions" RENAME CONSTRAINT "ListingRevision_listingId_fkey" TO "listing_revisions_listing_id_fkey";
ALTER TABLE "listing_revisions" RENAME CONSTRAINT "ListingRevision_listingId_version_key" TO "listing_revisions_listing_id_version_key";
ALTER TABLE "media_assets" RENAME CONSTRAINT "MediaAsset_pkey" TO "media_assets_pkey";
ALTER TABLE "media_assets" RENAME CONSTRAINT "MediaAsset_listingId_fkey" TO "media_assets_listing_id_fkey";
ALTER TABLE "catalog_import_jobs" RENAME CONSTRAINT "CatalogImportJob_pkey" TO "catalog_import_jobs_pkey";
ALTER TABLE "catalog_import_jobs" RENAME CONSTRAINT "CatalogImportJob_vendorId_fkey" TO "catalog_import_jobs_vendor_id_fkey";
ALTER TABLE "catalog_import_jobs" RENAME CONSTRAINT "CatalogImportJob_vendorId_sourceHash_mode_key" TO "catalog_import_jobs_vendor_id_source_hash_mode_key";
ALTER TABLE "catalog_import_rows" RENAME CONSTRAINT "CatalogImportRow_pkey" TO "catalog_import_rows_pkey";
ALTER TABLE "catalog_import_rows" RENAME CONSTRAINT "CatalogImportRow_importJobId_fkey" TO "catalog_import_rows_import_job_id_fkey";
ALTER TABLE "catalog_import_rows" RENAME CONSTRAINT "CatalogImportRow_importJobId_rowNumber_key" TO "catalog_import_rows_import_job_id_row_number_key";
ALTER TABLE "search_documents" RENAME CONSTRAINT "SearchDocument_pkey" TO "search_documents_pkey";
ALTER TABLE "search_documents" RENAME CONSTRAINT "SearchDocument_listingId_fkey" TO "search_documents_listing_id_fkey";
ALTER TABLE "locations" RENAME CONSTRAINT "Location_pkey" TO "locations_pkey";
ALTER TABLE "locations" RENAME CONSTRAINT "Location_vendorId_fkey" TO "locations_vendor_id_fkey";
ALTER TABLE "vendor_memberships" RENAME CONSTRAINT "VendorMembership_pkey" TO "vendor_memberships_pkey";
ALTER TABLE "vendor_memberships" RENAME CONSTRAINT "VendorMembership_staffId_key" TO "vendor_memberships_staff_id_key";
ALTER TABLE "vendor_memberships" RENAME CONSTRAINT "VendorMembership_userId_fkey" TO "vendor_memberships_user_id_fkey";
ALTER TABLE "vendor_memberships" RENAME CONSTRAINT "VendorMembership_vendorId_fkey" TO "vendor_memberships_vendor_id_fkey";
ALTER TABLE "vendor_memberships" RENAME CONSTRAINT "VendorMembership_staffId_fkey" TO "vendor_memberships_staff_id_fkey";
ALTER TABLE "vendor_memberships" RENAME CONSTRAINT "VendorMembership_userId_vendorId_key" TO "vendor_memberships_user_id_vendor_id_key";
ALTER TABLE "staff_members" RENAME CONSTRAINT "Staff_pkey" TO "staff_members_pkey";
ALTER TABLE "staff_members" RENAME CONSTRAINT "Staff_vendorId_fkey" TO "staff_members_vendor_id_fkey";
ALTER TABLE "staff_members" RENAME CONSTRAINT "Staff_userId_fkey" TO "staff_members_user_id_fkey";
ALTER TABLE "staff_members" RENAME CONSTRAINT "Staff_vendorId_userId_key" TO "staff_members_vendor_id_user_id_key";
ALTER TABLE "idempotency_records" RENAME CONSTRAINT "IdempotencyRecord_pkey" TO "idempotency_records_pkey";
ALTER TABLE "idempotency_records" RENAME CONSTRAINT "IdempotencyRecord_key_scopeHash_method_key" TO "idempotency_records_key_scope_hash_method_key";
ALTER TABLE "outbox_events" RENAME CONSTRAINT "OutboxEvent_pkey" TO "outbox_events_pkey";
ALTER TABLE "outbox_events" RENAME CONSTRAINT "OutboxEvent_eventId_key" TO "outbox_events_event_id_key";
ALTER TABLE "provider_inbox_events" RENAME CONSTRAINT "ProviderInboxEvent_pkey" TO "provider_inbox_events_pkey";
ALTER TABLE "provider_inbox_events" RENAME CONSTRAINT "ProviderInboxEvent_provider_providerEventId_key" TO "provider_inbox_events_provider_provider_event_id_key";
ALTER TABLE "demo_workspaces" RENAME CONSTRAINT "DemoWorkspace_pkey" TO "demo_workspaces_pkey";
ALTER TABLE "demo_workspaces" RENAME CONSTRAINT "DemoWorkspace_workspaceId_fkey" TO "demo_workspaces_workspace_id_fkey";
ALTER TABLE "demo_personas" RENAME CONSTRAINT "DemoPersona_pkey" TO "demo_personas_pkey";
ALTER TABLE "demo_personas" RENAME CONSTRAINT "DemoPersona_workspaceId_fkey" TO "demo_personas_workspace_id_fkey";
ALTER TABLE "demo_personas" RENAME CONSTRAINT "DemoPersona_workspaceId_key_key" TO "demo_personas_workspace_id_key_key";
ALTER TABLE "audit_logs" RENAME CONSTRAINT "AuditLog_pkey" TO "audit_logs_pkey";
ALTER TABLE "outbox_receipts" RENAME CONSTRAINT "OutboxReceipt_pkey" TO "outbox_receipts_pkey";
ALTER INDEX "Session_workspaceId_expiresAt_idx" RENAME TO "sessions_workspace_id_expires_at_idx";
ALTER INDEX "Vendor_workspaceId_idx" RENAME TO "vendors_workspace_id_idx";
ALTER INDEX "Vendor_publishedAt_id_idx" RENAME TO "vendors_published_at_id_idx";
ALTER INDEX "VendorFollow_vendorId_createdAt_idx" RENAME TO "vendor_follows_vendor_id_created_at_idx";
ALTER INDEX "SavedSearch_userId_workspaceId_idx" RENAME TO "saved_searches_user_id_workspace_id_idx";
ALTER INDEX "Listing_vendorId_state_idx" RENAME TO "listings_vendor_id_state_idx";
ALTER INDEX "Listing_kind_state_publishedAt_idx" RENAME TO "listings_kind_state_published_at_idx";
ALTER INDEX "ListingVariant_listingId_idx" RENAME TO "listing_variants_listing_id_idx";
ALTER INDEX "ListingRevision_state_createdAt_idx" RENAME TO "listing_revisions_state_created_at_idx";
ALTER INDEX "MediaAsset_listingId_state_idx" RENAME TO "media_assets_listing_id_state_idx";
ALTER INDEX "SearchDocument_kind_category_title_idx" RENAME TO "search_documents_kind_category_title_idx";
ALTER INDEX "Location_vendorId_idx" RENAME TO "locations_vendor_id_idx";
ALTER INDEX "VendorMembership_vendorId_revokedAt_idx" RENAME TO "vendor_memberships_vendor_id_revoked_at_idx";
ALTER INDEX "Staff_userId_idx" RENAME TO "staff_members_user_id_idx";
ALTER INDEX "IdempotencyRecord_expiresAt_idx" RENAME TO "idempotency_records_expires_at_idx";
ALTER INDEX "OutboxEvent_state_occurredAt_idx" RENAME TO "outbox_events_state_occurred_at_idx";
ALTER INDEX "OutboxEvent_workspaceId_occurredAt_idx" RENAME TO "outbox_events_workspace_id_occurred_at_idx";
ALTER INDEX "OutboxEvent_claim_idx" RENAME TO "outbox_events_claim_idx";
ALTER INDEX "ProviderInboxEvent_reconciliation_idx" RENAME TO "provider_inbox_events_reconciliation_idx";
ALTER INDEX "DemoWorkspace_expiresAt_purgedAt_idx" RENAME TO "demo_workspaces_expires_at_purged_at_idx";
ALTER INDEX "DemoPersona_workspaceId_role_idx" RENAME TO "demo_personas_workspace_id_role_idx";
ALTER INDEX "AuditLog_workspaceId_createdAt_idx" RENAME TO "audit_logs_workspace_id_created_at_idx";
